#
version: '2'

volumes:
  mysql:
  files:
  deleted:

services:
  app:
    extends:
      file: common.yml
      service: app
    image: buckett/sakai-tomcat
  
    # Not too sure about this as there seem to be IO errors with using volumes like
    # this, eg corrupt files and missing files.
    # We use the sakai.properties from the production build
    volumes:
     - ./tomcat/lib:/opt/tomcat/sakai-lib
     - ./tomcat/components:/opt/tomcat/components
     - ./tomcat/webapps:/opt/tomcat/webapps
     - ./placeholder.properties:/opt/tomcat/sakai/placeholder.properties
     - ./sakai.quartz.properties:/opt/tomcat/sakai/sakai.quartz.properties
     - ./log4j.properties:/opt/tomcat/sakai/log4j.properties
     - ./local.properties:/opt/tomcat/sakai/local.properties
     - ./override:/opt/tomcat/sakai/override
    command: /opt/tomcat/bin/catalina.sh jpda run
    environment:
     # In development this means we can read files without anything special
     SAKAI_USER: root
    links:
     - db
     #- ldap
  
  #ldap:
    #image: inanimate/ncat-proxy
    #environment:
     #DEST_HOST: ldap.forumsys.com
     #DEST_PORT: 389
     #LOCAL_PORT: 389
    #command: ncat -l -p 389 -k --sh-exec "ncat ldap.forumsys.com 389"
  
  db:
    extends:
      file: common.yml
      service: db
    volumes:
      - mysql:/var/lib/mysql
    #ports:
    # - 3307:3306
